// @vitest-environment jsdom
import { act, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { AppField } from '../field'
import { AppNumberBox } from './AppNumberBox'

describe('AppNumberBox', () => {
  let host: HTMLDivElement; let root: ReturnType<typeof createRoot>
  beforeEach(() => { ;(globalThis as { IS_REACT_ACT_ENVIRONMENT?: boolean }).IS_REACT_ACT_ENVIRONMENT = true; host = document.createElement('div'); document.body.append(host); root = createRoot(host) })
  afterEach(() => { act(() => root.unmount()); host.remove() })
  const input = () => host.querySelector<HTMLInputElement>('input')!
  const setText = (text: string) => act(() => { const setter = Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value')?.set; setter?.call(input(), text); input().dispatchEvent(new Event('input', { bubbles: true })) })
  const key = (value: string, options: KeyboardEventInit = {}) => act(() => input().dispatchEvent(new KeyboardEvent('keydown', { bubbles: true, key: value, ...options })))
  const blur = () => act(() => input().dispatchEvent(new FocusEvent('focusout', { bubbles: true })))
  const pointerDown = (button: HTMLButtonElement) => { const event = new PointerEvent('pointerdown', { bubbles: true, cancelable: true }); act(() => button.dispatchEvent(event)); return event }

  it('steps, clamps, and applies precision in uncontrolled mode', () => { const changed = vi.fn(); act(() => root.render(<AppNumberBox defaultValue={9.8} max={10} onValueChange={changed} precision={1} step={0.3} />)); act(() => host.querySelector('button')?.click()); expect(input().value).toBe('10'); expect(changed).toHaveBeenCalledWith(10) })
  it('starts stepping from zero when the input is empty', () => { const changed = vi.fn(); act(() => root.render(<AppNumberBox onValueChange={changed} step={2} />)); act(() => host.querySelector<HTMLButtonElement>('button')?.click()); expect(input().value).toBe('2'); expect(changed).toHaveBeenCalledWith(2) })
  it('steps from valid pending input without requiring blur', () => { const changed = vi.fn(); act(() => root.render(<AppNumberBox onValueChange={changed} />)); setText('5'); const increment = host.querySelector<HTMLButtonElement>('button')!; expect(increment.disabled).toBe(false); act(() => increment.click()); expect(input().value).toBe('6'); expect(changed).toHaveBeenCalledWith(6) })
  it('uses step for pointer buttons and largeStep for fast keyboard changes', () => { const changed = vi.fn(); act(() => root.render(<AppNumberBox defaultValue={5} largeStep={10} onValueChange={changed} step={2} />)); act(() => host.querySelector<HTMLButtonElement>('button')?.click()); expect(input().value).toBe('7'); key('ArrowUp', { shiftKey: true }); expect(input().value).toBe('17'); key('PageDown'); expect(input().value).toBe('7'); expect(changed).toHaveBeenLastCalledWith(7) })
  it('prevents blur and submits pending input only once when stepping', () => { const changed = vi.fn(); act(() => root.render(<AppNumberBox onValueChange={changed} />)); act(() => input().focus()); setText('5'); const increment = host.querySelector<HTMLButtonElement>('button')!; const event = pointerDown(increment); expect(event.defaultPrevented).toBe(true); expect(document.activeElement).toBe(input()); act(() => increment.click()); expect(changed).toHaveBeenCalledTimes(1); expect(changed).toHaveBeenLastCalledWith(6); expect(input().value).toBe('6'); expect(document.activeElement).toBe(input()) })
  it('submits once when a controlled parent accepts a pointer step', () => { const changed = vi.fn(); function Harness() { const [value, setValue] = useState<number | null>(null); return <AppNumberBox onValueChange={(next) => { changed(next); setValue(next) }} value={value} /> } act(() => root.render(<Harness />)); act(() => input().focus()); setText('5'); const increment = host.querySelector<HTMLButtonElement>('button')!; expect(pointerDown(increment).defaultPrevented).toBe(true); act(() => increment.click()); expect(changed).toHaveBeenCalledTimes(1); expect(changed).toHaveBeenCalledWith(6); expect(input().value).toBe('6'); expect(document.activeElement).toBe(input()) })
  it('supports Arrow keys, Enter commit, and Escape restore', () => { const changed = vi.fn(); act(() => root.render(<AppNumberBox defaultValue={2} onValueChange={changed} />)); key('ArrowUp'); expect(input().value).toBe('3'); setText('7'); key('Enter'); expect(changed).toHaveBeenLastCalledWith(7); setText('99'); key('Escape'); expect(input().value).toBe('7'); key('ArrowDown'); expect(input().value).toBe('6') })
  it('commits allowed empty values and restores disallowed or invalid text', () => { const changed = vi.fn(); act(() => root.render(<AppNumberBox allowEmpty defaultValue={2} onValueChange={changed} />)); setText(''); blur(); expect(changed).toHaveBeenCalledWith(null); act(() => root.render(<AppNumberBox defaultValue={4} key="fresh" onValueChange={changed} />)); setText('invalid'); blur(); expect(input().value).toBe('4'); setText(''); blur(); expect(input().value).toBe('4') })
  it('still commits pending input on a real outside blur', () => { const changed = vi.fn(); act(() => root.render(<><AppNumberBox onValueChange={changed} /><button type="button">Outside</button></>)); act(() => input().focus()); setText('5'); blur(); expect(changed).toHaveBeenCalledOnce(); expect(changed).toHaveBeenCalledWith(5) })
  it('accepts controlled updates from the parent', () => { function Harness() { const [value, setValue] = useState(2); return <AppNumberBox onValueChange={(next) => { if (next != null) setValue(next) }} value={value} /> } act(() => root.render(<Harness />)); act(() => host.querySelector('button')?.click()); expect(input().value).toBe('3') })
  it('restores controlled text when the parent rejects an update', () => { const changed = vi.fn(); act(() => root.render(<AppNumberBox onValueChange={changed} value={2} />)); act(() => host.querySelector('button')?.click()); expect(changed).toHaveBeenCalledWith(3); expect(input().value).toBe('2'); setText('5'); blur(); expect(input().value).toBe('2') })
  it('synchronizes external controlled value changes', () => { act(() => root.render(<AppNumberBox value={2} />)); act(() => root.render(<AppNumberBox value={8} />)); expect(input().value).toBe('8') })
  it('supports hidden and compact spin button placement', () => { act(() => root.render(<AppNumberBox defaultValue={2} spinButtonPlacement="hidden" />)); expect(host.querySelectorAll('button')).toHaveLength(0); act(() => root.render(<AppNumberBox defaultValue={2} spinButtonPlacement="compact" />)); act(() => input().focus()); const panel = document.body.querySelector<HTMLElement>('.app-number-box__compact-panel'); expect(panel).not.toBeNull(); expect(panel?.querySelectorAll('button')).toHaveLength(2); expect(panel?.querySelector('svg')).not.toBeNull(); act(() => panel?.querySelector<HTMLButtonElement>('button')?.click()); expect(input().value).toBe('3') })
  it('exposes spinbutton and field semantics', () => { act(() => root.render(<AppField description="Duration help" error="Invalid" id="duration" label="Duration"><AppNumberBox max={10} min={1} value={4} /></AppField>)); expect(input().getAttribute('role')).toBe('spinbutton'); expect(input().getAttribute('aria-valuemin')).toBe('1'); expect(input().getAttribute('aria-valuemax')).toBe('10'); expect(input().getAttribute('aria-valuenow')).toBe('4'); expect(input().getAttribute('aria-valuetext')).toBe('4'); expect(input().getAttribute('aria-describedby')).toBe(host.querySelector('.app-field__message')?.id); expect(input().getAttribute('aria-invalid')).toBe('true'); expect(host.querySelector('.app-number-box')?.classList).toContain('app-input-frame--invalid') })
  it('applies className to the number box root', () => { act(() => root.render(<AppNumberBox className="custom-number-box" />)); expect(host.querySelector('.app-number-box')?.classList).toContain('custom-number-box'); expect(input().classList).not.toContain('custom-number-box') })
  it('does not submit from disabled or read-only controls', () => { const changed = vi.fn(); act(() => root.render(<><AppNumberBox defaultValue={2} disabled onValueChange={changed} /><AppNumberBox defaultValue={3} onValueChange={changed} readOnly /></>)); const inputs = host.querySelectorAll<HTMLInputElement>('input'); act(() => inputs[0]?.dispatchEvent(new KeyboardEvent('keydown', { bubbles: true, key: 'ArrowUp' }))); act(() => inputs[1]?.dispatchEvent(new KeyboardEvent('keydown', { bubbles: true, key: 'ArrowUp' }))); host.querySelectorAll('button').forEach((button) => act(() => button.click())); expect(changed).not.toHaveBeenCalled() })
})
