// @vitest-environment jsdom
import { act, createRef, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { AppField } from '../field'
import { AppNumberBox } from './AppNumberBox'
import { AppSelect } from './AppSelect'

describe('number and select controls', () => {
  let host: HTMLDivElement; let root: ReturnType<typeof createRoot>
  beforeEach(() => { ;(globalThis as { IS_REACT_ACT_ENVIRONMENT?: boolean }).IS_REACT_ACT_ENVIRONMENT = true; host = document.createElement('div'); document.body.append(host); root = createRoot(host) })
  afterEach(() => { act(() => root.unmount()); host.remove() })
  const input = () => host.querySelector<HTMLInputElement>('input')!
  const setText = (text: string) => act(() => { const setter = Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value')?.set; setter?.call(input(), text); input().dispatchEvent(new Event('input', { bubbles: true })) })
  const key = (value: string) => act(() => input().dispatchEvent(new KeyboardEvent('keydown', { bubbles: true, key: value })))
  const blur = () => act(() => input().dispatchEvent(new FocusEvent('focusout', { bubbles: true })))

  it('steps, clamps, and applies precision in uncontrolled mode', () => { const changed = vi.fn(); act(() => root.render(<AppNumberBox defaultValue={9.8} max={10} onValueChange={changed} precision={1} step={0.3} />)); act(() => host.querySelector('button')?.click()); expect(input().value).toBe('10'); expect(changed).toHaveBeenCalledWith(10) })
  it('supports Arrow keys, Enter commit, and Escape restore', () => { const changed = vi.fn(); act(() => root.render(<AppNumberBox defaultValue={2} onValueChange={changed} />)); key('ArrowUp'); expect(input().value).toBe('3'); setText('7'); key('Enter'); expect(changed).toHaveBeenLastCalledWith(7); setText('99'); key('Escape'); expect(input().value).toBe('7'); key('ArrowDown'); expect(input().value).toBe('6') })
  it('commits allowed empty values and restores disallowed or invalid text', () => { const changed = vi.fn(); act(() => root.render(<AppNumberBox allowEmpty defaultValue={2} onValueChange={changed} />)); setText(''); blur(); expect(changed).toHaveBeenCalledWith(null); act(() => root.render(<AppNumberBox defaultValue={4} key="fresh" onValueChange={changed} />)); setText('invalid'); blur(); expect(input().value).toBe('4'); setText(''); blur(); expect(input().value).toBe('4') })
  it('accepts controlled updates from the parent', () => { function Harness() { const [value, setValue] = useState(2); return <AppNumberBox onValueChange={(next) => { if (next != null) setValue(next) }} value={value} /> } act(() => root.render(<Harness />)); act(() => host.querySelector('button')?.click()); expect(input().value).toBe('3') })
  it('restores controlled text when the parent rejects an update', () => { const changed = vi.fn(); act(() => root.render(<AppNumberBox onValueChange={changed} value={2} />)); act(() => host.querySelector('button')?.click()); expect(changed).toHaveBeenCalledWith(3); expect(input().value).toBe('2'); setText('5'); blur(); expect(input().value).toBe('2') })
  it('synchronizes external controlled value changes', () => { act(() => root.render(<AppNumberBox value={2} />)); act(() => root.render(<AppNumberBox value={8} />)); expect(input().value).toBe('8') })
  it('exposes spinbutton and field semantics', () => { act(() => root.render(<AppField description="Duration help" error="Invalid" id="duration" label="Duration"><AppNumberBox max={10} min={1} value={4} /></AppField>)); expect(input().getAttribute('role')).toBe('spinbutton'); expect(input().getAttribute('aria-valuemin')).toBe('1'); expect(input().getAttribute('aria-valuemax')).toBe('10'); expect(input().getAttribute('aria-valuenow')).toBe('4'); expect(input().getAttribute('aria-valuetext')).toBe('4'); expect(input().getAttribute('aria-describedby')).toBe(host.querySelector('.app-field__message')?.id); expect(input().getAttribute('aria-invalid')).toBe('true') })
  it('does not submit from disabled or read-only controls', () => { const changed = vi.fn(); act(() => root.render(<><AppNumberBox defaultValue={2} disabled onValueChange={changed} /><AppNumberBox defaultValue={3} onValueChange={changed} readOnly /></>)); const inputs = host.querySelectorAll<HTMLInputElement>('input'); act(() => inputs[0]?.dispatchEvent(new KeyboardEvent('keydown', { bubbles: true, key: 'ArrowUp' }))); act(() => inputs[1]?.dispatchEvent(new KeyboardEvent('keydown', { bubbles: true, key: 'ArrowUp' }))); host.querySelectorAll('button').forEach((button) => act(() => button.click())); expect(changed).not.toHaveBeenCalled() })
  it('changes native select values and preserves form attributes', () => { const changed = vi.fn(); const ref = createRef<HTMLSelectElement>(); act(() => root.render(<AppSelect name="course" onValueChange={changed} options={[{ value: 'one', label: 'One' }, { value: 'two', label: 'Two', disabled: true }]} ref={ref} />)); act(() => { ref.current!.value = 'one'; ref.current!.dispatchEvent(new Event('change', { bubbles: true })) }); expect(changed).toHaveBeenCalledWith('one'); expect(ref.current?.name).toBe('course'); expect(ref.current?.querySelectorAll('option')[1]?.disabled).toBe(true) })
  it('supports placeholder, controlled, uncontrolled, and Field context', () => { const changed = vi.fn(); act(() => root.render(<AppField description="Choose one" id="choice" label="Choice"><AppSelect defaultValue="1" name="choice" onValueChange={changed} options={[{ value: '1', label: 'One' }]} placeholder="Choose" /></AppField>)); const select = host.querySelector('select')!; expect(select.value).toBe('1'); expect(select.name).toBe('choice'); expect(select.id).toBe('choice'); expect(select.getAttribute('aria-describedby')).toBe(host.querySelector('.app-field__message')?.id); act(() => root.render(<AppSelect onValueChange={changed} options={[{ value: '1', label: 'One' }, { value: '2', label: 'Two' }]} value="2" />)); expect(host.querySelector('select')?.value).toBe('2') })
})
