import { forwardRef, useEffect, useState } from 'react'; import type { FocusEvent, KeyboardEvent } from 'react'; import { useAppFieldContext } from '../field/AppFieldContext'; import type { AppNumberBoxProps } from './types'; import './AppNumberSelect.css'
const clamp = (value: number, min?: number, max?: number) => Math.min(max ?? Number.POSITIVE_INFINITY, Math.max(min ?? Number.NEGATIVE_INFINITY, value))
const round = (value: number, precision?: number) => precision == null ? value : Number(value.toFixed(Math.max(0, precision)))
export const AppNumberBox = forwardRef<HTMLInputElement, AppNumberBoxProps>(function AppNumberBox({ 'aria-describedby': ariaDescribedBy, 'aria-invalid': ariaInvalid, allowEmpty = false, defaultValue = null, decrementLabel = 'Decrease value', disabled, formatValue = String, id, incrementLabel = 'Increase value', max, min, onBlur, onKeyDown, onValueChange, parseValue = (text) => { const value = Number(text); return text.trim() === '' || !Number.isFinite(value) ? null : value }, precision, readOnly = false, required, step = 1, value, ...rest }, ref) {
  const field = useAppFieldContext(); const resolvedDisabled = disabled ?? field?.disabled ?? false
  const controlled = value !== undefined; const [internal, setInternal] = useState<number | null>(defaultValue); const resolved = controlled ? value : internal; const [text, setText] = useState(() => resolved == null ? '' : formatValue(resolved))
  useEffect(() => { if (controlled) setText(value == null ? '' : formatValue(value)) }, [controlled, formatValue, value])
  const commit = (next: number | null) => { let normalized = next; if (normalized == null && !allowEmpty) normalized = clamp(0, min, max); if (normalized != null) normalized = round(clamp(normalized, min, max), precision); if (!controlled) setInternal(normalized); setText(normalized == null ? '' : formatValue(normalized)); if (normalized !== resolved) onValueChange?.(normalized) }
  const changeBy = (direction: number) => commit(round((parseValue(text) ?? resolved ?? 0) + step * direction, precision))
  const handleBlur = (event: FocusEvent<HTMLInputElement>) => { commit(parseValue(text)); onBlur?.(event) }
  const handleKey = (event: KeyboardEvent<HTMLInputElement>) => { onKeyDown?.(event); if (event.defaultPrevented || resolvedDisabled || readOnly) return; if (event.key === 'ArrowUp' || event.key === 'ArrowDown') { event.preventDefault(); changeBy(event.key === 'ArrowUp' ? 1 : -1) } }
  return <span className={`app-number-box${resolvedDisabled ? ' app-number-box--disabled' : ''}`}><input {...rest} aria-describedby={ariaDescribedBy ?? field?.describedBy} aria-invalid={(ariaInvalid ?? field?.invalid) || undefined} disabled={resolvedDisabled} id={id ?? field?.controlId} inputMode="decimal" onBlur={handleBlur} onChange={(event) => setText(event.target.value)} onKeyDown={handleKey} readOnly={readOnly} ref={ref} required={required ?? field?.required} type="text" value={text} /><span className="app-number-box__buttons"><button aria-label={incrementLabel} disabled={resolvedDisabled || readOnly || (resolved != null && max != null && resolved >= max)} onClick={() => changeBy(1)} type="button">+</button><button aria-label={decrementLabel} disabled={resolvedDisabled || readOnly || (resolved != null && min != null && resolved <= min)} onClick={() => changeBy(-1)} type="button">−</button></span></span>
})
