// @vitest-environment jsdom
import { act } from 'react'; import { createRoot, type Root } from 'react-dom/client'; import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'; import { AppMultiSelect } from './AppMultiSelect'
import { AppShell } from '../shell/AppShell'
const options = [{ value: 'design', label: 'Design' }, { value: 'engineering', label: 'Engineering' }, { value: 'research', label: 'Research' }]
describe('AppMultiSelect', () => { let container: HTMLDivElement; let root: Root
  beforeEach(() => { ;(globalThis as { IS_REACT_ACT_ENVIRONMENT?: boolean }).IS_REACT_ACT_ENVIRONMENT = true; container = document.createElement('div'); document.body.append(container); root = createRoot(container) })
  afterEach(() => { act(() => root.unmount()); container.remove() })
  it('adds and removes selected values', () => { const onValueChange = vi.fn(); act(() => root.render(<AppMultiSelect onValueChange={onValueChange} options={options} />)); act(() => container.querySelector('input')!.focus()); expect(container.contains(document.body.querySelector('.app-multi-select__list'))).toBe(false); act(() => Array.from(document.body.querySelectorAll<HTMLButtonElement>('.app-multi-select__list button')).find((button) => button.textContent === 'Engineering')!.click()); expect(onValueChange).toHaveBeenLastCalledWith(['engineering']); act(() => container.querySelector<HTMLButtonElement>('[aria-label="Remove Engineering"]')!.click()); expect(onValueChange).toHaveBeenLastCalledWith([]) })
  it('filters options and enforces a maximum', () => { act(() => root.render(<AppMultiSelect defaultValue={['design']} maxSelected={1} options={options} />)); const input = container.querySelector('input')!; act(() => { input.focus(); const setter = Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value')!.set!; setter.call(input, 'res'); input.dispatchEvent(new Event('input', { bubbles: true })) }); expect(document.body.querySelector('.app-multi-select__list')?.textContent).toContain('Research'); expect(document.body.querySelector<HTMLButtonElement>('.app-multi-select__list [role="option"]')!.disabled).toBe(true) })
  it('portals the list into the AppShell overlay host', () => { act(() => root.render(<AppShell><div style={{ overflow: 'hidden' }}><AppMultiSelect options={options} /></div></AppShell>)); act(() => container.querySelector('input')!.focus()); const overlayHost = container.querySelector('.app-shell__overlay-host'); const popup = overlayHost?.querySelector('.app-multi-select__list'); expect(popup).not.toBeNull(); expect(popup?.closest('[style*="overflow: hidden"]')).toBeNull() })
})
