import { useRef, useState, type KeyboardEvent, type PointerEvent } from 'react'; import { useAppLocale } from '../localization/useAppLocale'; import type { AppResizablePaneGroupProps } from './types'; import './AppResizablePaneGroup.css'
export function AppResizablePaneGroup({ children, className, defaultSize = 280, disabled = false, maxSize = 640, minSize = 160, onSizeChange, orientation = 'horizontal', resizeLabel, size, style }: AppResizablePaneGroupProps) {
  const { messages } = useAppLocale()
  const [internal, setInternal] = useState(defaultSize); const current = Math.min(maxSize, Math.max(minSize, size ?? internal)); const groupRef = useRef<HTMLDivElement>(null); const controlled = size !== undefined
  const update = (next: number) => { const bounded = Math.min(maxSize, Math.max(minSize, Math.round(next))); if (!controlled) setInternal(bounded); if (bounded !== current) onSizeChange?.(bounded) }
  const startDrag = (event: PointerEvent<HTMLDivElement>) => { if (disabled) return; event.currentTarget.setPointerCapture(event.pointerId); const rect = groupRef.current?.getBoundingClientRect(); if (!rect) return; const move = (next: globalThis.PointerEvent) => update(orientation === 'horizontal' ? next.clientX - rect.left : next.clientY - rect.top); const end = () => { document.removeEventListener('pointermove', move); document.removeEventListener('pointerup', end) }; document.addEventListener('pointermove', move); document.addEventListener('pointerup', end) }
  const key = (event: KeyboardEvent) => { const delta = event.shiftKey ? 50 : 10; const decrease = orientation === 'horizontal' ? event.key === 'ArrowLeft' : event.key === 'ArrowUp'; const increase = orientation === 'horizontal' ? event.key === 'ArrowRight' : event.key === 'ArrowDown'; if (decrease || increase) { event.preventDefault(); update(current + (increase ? delta : -delta)) } else if (event.key === 'Home') { event.preventDefault(); update(minSize) } else if (event.key === 'End') { event.preventDefault(); update(maxSize) } }
  return <div className={['app-resizable-panes', `app-resizable-panes--${orientation}`, className].filter(Boolean).join(' ')} ref={groupRef} style={style}><div className="app-resizable-panes__primary" style={{ flexBasis: current }}>{children[0]}</div><div aria-label={resizeLabel ?? messages.resizablePane.resize} aria-orientation={orientation} aria-valuemax={maxSize} aria-valuemin={minSize} aria-valuenow={current} className="app-resizable-panes__separator" onKeyDown={key} onPointerDown={startDrag} role="separator" tabIndex={disabled ? -1 : 0}><span /></div><div className="app-resizable-panes__secondary">{children[1]}</div></div>
}
