// @vitest-environment jsdom
import { act, createRef } from 'react'; import { createRoot } from 'react-dom/client'; import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'; import { AppCheckBox } from './AppCheckBox'; import { AppRadioGroup } from './AppRadioGroup'; import { AppSegmentedControl } from './AppSegmentedControl'; import { AppToggleSwitch } from './AppToggleSwitch'
describe('selection controls', () => { let host: HTMLDivElement; let root: ReturnType<typeof createRoot>; beforeEach(() => { ;(globalThis as { IS_REACT_ACT_ENVIRONMENT?: boolean }).IS_REACT_ACT_ENVIRONMENT = true; host = document.createElement('div'); document.body.append(host); root = createRoot(host) }); afterEach(() => { act(() => root.unmount()); host.remove() }); const input = () => host.querySelector('input')!
  it('keeps uncontrolled indeterminate state synchronized after interaction', () => { const changed = vi.fn(); const ref = createRef<HTMLInputElement>(); act(() => root.render(<AppCheckBox indeterminate label="Select" onCheckedChange={changed} ref={ref} />)); expect(ref.current?.indeterminate).toBe(true); expect(input().getAttribute('aria-checked')).toBe('mixed'); act(() => input().click()); expect(changed).toHaveBeenCalledWith(true); expect(input().indeterminate).toBe(true); expect(input().getAttribute('aria-checked')).toBe('mixed'); act(() => root.render(<AppCheckBox indeterminate={false} label="Select" onCheckedChange={changed} ref={ref} />)); expect(input().indeterminate).toBe(false); expect(input().checked).toBe(true); expect(input().getAttribute('aria-checked')).toBe('true') })
  it('keeps controlled checked and indeterminate states synchronized', () => { const changed = vi.fn(); act(() => root.render(<AppCheckBox checked={false} indeterminate onCheckedChange={changed} />)); act(() => input().click()); expect(changed).toHaveBeenCalledWith(true); expect(input().checked).toBe(false); expect(input().indeterminate).toBe(true); expect(input().getAttribute('aria-checked')).toBe('mixed') })
  it('keeps controlled checkbox state and native form values', () => { const changed = vi.fn(); act(() => root.render(<AppCheckBox checked={false} name="choice" onCheckedChange={changed} value="yes" />)); act(() => input().click()); expect(input().checked).toBe(false); expect(input().name).toBe('choice'); expect(input().value).toBe('yes') })
  it('uses switch semantics and supports Enter', () => { const changed = vi.fn(); act(() => root.render(<AppToggleSwitch label="Preview" onCheckedChange={changed} />)); act(() => input().dispatchEvent(new KeyboardEvent('keydown', { bubbles: true, key: 'Enter' }))); expect(changed).toHaveBeenCalledWith(true); expect(input().getAttribute('role')).toBe('switch'); expect(input().getAttribute('aria-checked')).toBe('true') })
  it('does not toggle disabled controls', () => { const changed = vi.fn(); act(() => root.render(<AppToggleSwitch disabled onCheckedChange={changed} />)); act(() => input().click()); expect(changed).not.toHaveBeenCalled() })
  it('does not toggle a disabled checkbox', () => { const changed = vi.fn(); act(() => root.render(<AppCheckBox disabled indeterminate onCheckedChange={changed} />)); act(() => input().click()); expect(changed).not.toHaveBeenCalled(); expect(input().checked).toBe(false); expect(input().indeterminate).toBe(true) })
  it('supports controlled radio-group selection and native form attributes', () => { const changed = vi.fn(); act(() => root.render(<AppRadioGroup ariaLabel="Density" name="density" onValueChange={changed} options={[{value:'compact',label:'Compact'},{value:'comfortable',label:'Comfortable'},{value:'managed',label:'Managed',disabled:true}]} value="compact"/>)); const inputs=host.querySelectorAll<HTMLInputElement>('input'); expect(inputs[0]?.checked).toBe(true); expect(inputs[0]?.name).toBe('density'); act(() => inputs[1]?.click()); expect(changed).toHaveBeenCalledWith('comfortable'); expect(inputs[0]?.checked).toBe(true); act(() => inputs[2]?.click()); expect(changed).toHaveBeenCalledTimes(1) })
  it('supports uncontrolled segmented selection', () => { const changed = vi.fn(); act(() => root.render(<AppSegmentedControl ariaLabel="Layout" defaultValue="list" onValueChange={changed} options={[{value:'list',label:'List'},{value:'grid',label:'Grid'}]}/>)); const inputs=host.querySelectorAll<HTMLInputElement>('input'); expect(inputs[0]?.checked).toBe(true); act(() => inputs[1]?.click()); expect(inputs[1]?.checked).toBe(true); expect(changed).toHaveBeenCalledWith('grid'); expect(host.querySelector('[role="radiogroup"]')).not.toBeNull() })
})
