// @vitest-environment jsdom
import { act } from 'react'; import { createRoot } from 'react-dom/client'; import { afterEach, beforeEach, describe, expect, it } from 'vitest'
import { AppProgressBar } from './AppProgressBar'; import { AppProgressRing } from './AppProgressRing'; import { AppStatusBadge } from './AppStatusBadge'
describe('progress and status', () => { let host: HTMLDivElement; let root: ReturnType<typeof createRoot>; beforeEach(() => { ;(globalThis as { IS_REACT_ACT_ENVIRONMENT?: boolean }).IS_REACT_ACT_ENVIRONMENT = true; host = document.createElement('div'); document.body.append(host); root = createRoot(host) }); afterEach(() => { act(() => root.unmount()); host.remove() })
  it('clamps determinate values and exposes progress semantics', () => { act(() => root.render(<AppProgressBar max={100} showValue value={140} />)); const bar = host.querySelector('[role=progressbar]')!; expect(bar.getAttribute('aria-valuenow')).toBe('100'); expect(bar.getAttribute('aria-valuemin')).toBe('0'); expect(bar.getAttribute('aria-valuemax')).toBe('100'); expect(host.textContent).toContain('100%') })
  it('omits numeric aria values while indeterminate', () => { act(() => root.render(<AppProgressBar indeterminate label="Loading" />)); const bar = host.querySelector('[role=progressbar]')!; expect(bar.getAttribute('aria-valuenow')).toBeNull(); expect(host.querySelector('.app-progress-bar--indeterminate')).not.toBeNull() })
  it('keeps hidden ring labels accessible and identifies badge state', () => { act(() => root.render(<><AppProgressRing label="Checking" labelPosition="hidden" /><AppStatusBadge appearance="outline" status="success">Ready</AppStatusBadge></>)); expect(host.querySelector('[role=status]')?.getAttribute('aria-label')).toBe('Checking'); expect(host.querySelector('.app-status-badge')?.className).toContain('app-status-badge--success'); expect(host.textContent).toContain('Success:') })
  it('allows localized status text', () => { act(() => root.render(<AppStatusBadge status="success" statusLabel="成功">已完成</AppStatusBadge>)); expect(host.textContent).toBe('成功: 已完成') })
})
