export {
  Add16Regular as Plus,
  AlignLeft16Regular as AlignJustify,
  AlignLeft16Regular,
  ArrowBidirectionalLeftRight16Regular as ChevronsLeftRight,
  ArrowCollapseAll16Regular as ListCollapse,
  ArrowDownload16Regular as Download,
  ArrowSync16Regular as LoaderCircle,
  ArrowSync16Regular as RefreshCw,
  ArrowUp16Regular as ArrowUp,
  Box16Regular as Boxes,
  Branch16Regular as GitBranch,
  BroadActivityFeed16Regular as Activity,
  CheckmarkCircle16Regular as BadgeCheck,
  CalendarLtr16Regular as CalendarDays,
  CalendarLtr16Regular,
  CalendarMultiple16Regular as CalendarRange,
  Chat16Regular as MessageSquare,
  Chat16Regular as MessageSquareMore,
  Chat16Regular as MessageCircleQuestion,
  ChatHelp16Regular,
  ChatMultiple16Regular as MessagesSquare,
  Checkmark16Regular as Check,
  Checkmark16Regular,
  CheckmarkCircle16Regular as CheckCircle2,
  CheckmarkCircle16Regular as CircleCheck,
  CheckmarkCircle16Regular,
  CheckboxChecked16Regular as SquareCheck,
  ChevronDown16Regular as ChevronsUpDown,
  ChevronRight16Regular as ChevronRight,
  ChevronRight16Regular,
  Circle16Regular as CircleDot,
  Clock16Regular as Clock,
  Clock16Regular as Clock3,
  Cloud16Regular as Cloud,
  CloudArrowUp16Regular as UploadCloud,
  Code16Regular as Code2,
  Color16Regular as Palette,
  ColorFill16Regular as Blend,
  Copy16Regular as Copy,
  Cursor16Regular as MousePointer2,
  Cursor16Regular as SquareMousePointer,
  CursorHover16Regular as MousePointerClick,
  Database16Regular as Database,
  DatabaseArrowUp16Regular as DatabaseBackup,
  Delete16Regular as Trash2,
  Document16Regular,
  DocumentAdd16Regular as FilePlus2,
  DocumentArrowUp16Regular as FileUp,
  DocumentCode16Regular as FileCode2,
  DocumentImage16Regular as FileImage,
  DocumentSearch16Regular as SearchCode,
  DocumentTable16Regular as FileSpreadsheet,
  DocumentText16Regular as FileClock,
  DocumentText16Regular as FileText,
  DividerTall16Regular as SeparatorHorizontal,
  Edit16Regular as Pencil,
  ErrorCircle16Regular as XCircle,
  Filter16Regular as ListFilter,
  Filter16Regular,
  Folder16Regular as Folder,
  FolderOpen16Regular as FolderGit2,
  FolderOpen16Regular as FolderOpen,
  FolderOpen16Regular as FolderTree,
  Gauge16Regular as CircleGauge,
  Grid16Regular as LayoutDashboard,
  HardDrive16Regular as HardDrive,
  Heart16Regular as Heart,
  History16Regular as History,
  Home16Regular as Home,
  Info16Regular as BadgeInfo,
  Info16Regular as Info,
  Key16Regular as KeyRound,
  KeyCommand16Regular as Command,
  Keyboard16Regular as Keyboard,
  LayerDiagonal16Regular as Layers,
  LayoutColumnThree16Regular as Columns3,
  LayoutColumnTwo16Regular as Columns2,
  LayoutRowThree16Regular as Rows3,
  Link16Regular as Link,
  Lightbulb16Regular as Lightbulb,
  List16Regular as LayoutList,
  List16Regular as List,
  LocalLanguage16Regular as Languages,
  LockClosed16Regular as LockKeyhole,
  Mail16Regular as Mail,
  MailInbox16Regular as Inbox,
  Mic16Regular as Mic,
  MoreHorizontal16Regular as Ellipsis,
  MoreHorizontal16Regular as MoreHorizontal,
  MoreHorizontal16Regular,
  Navigation16Regular as Menu,
  Navigation16Regular as Navigation,
  Navigation16Regular,
  NumberSymbol16Regular as Hash,
  Open16Regular,
  Options16Regular as SlidersHorizontal,
  PanelLeft16Regular as BetweenHorizontalStart,
  PanelLeft16Regular as PanelLeft,
  PanelLeft16Regular as PanelsTopLeft,
  PanelLeft16Regular as Sidebar,
  PanelRight16Regular as PanelBottom,
  PanelRight16Regular as PanelRight,
  PanelRight16Regular,
  PanelTopGallery16Regular as LayoutPanelTop,
  PanelTopGallery16Regular as PanelTop,
  People16Regular as Users,
  Pen16Regular as PencilLine,
  Person16Regular as User,
  Person16Regular as UserRound,
  PersonAdd16Regular as UserPlus,
  Save16Regular as Save,
  Scan16Regular as ScanLine,
  Search16Regular as Search,
  Send16Regular as Send,
  ServiceBell16Regular as Bell,
  DocumentText16Regular as ScrollText,
  Settings16Regular as Settings,
  Settings16Regular as Settings2,
  Share16Regular as Share2,
  Sparkle16Regular as Sparkles,
  TaskListSquareLtr16Regular as ListChecks,
  TaskListSquareLtr16Regular as ListTodo,
  TextAlignLeft16Regular as AlignLeft,
  TextBold16Regular as Bold,
  TextBulletList16Regular as ListTree,
  TextBulletListTree16Regular,
  Textbox16Regular as TextCursorInput,
  TextItalic16Regular as Italic,
  TextUnderline16Regular as Underline,
  Textbox16Regular as FormInput,
  Table16Regular as Table2,
  TagMultiple16Regular as Tags,
  Timer16Regular as Timer,
  ToggleRight16Regular as ToggleRight,
  WalletCreditCard16Regular as CreditCard,
  Warning16Regular,
  Wand16Regular as WandSparkles,
  Window16Regular as AppWindow,
  PlugConnected16Regular as Wifi,
  Wrench16Regular as Wrench,
} from '@fluentui/react-icons'
