// @vitest-environment jsdom
import { act, createRef } from 'react'; import { createRoot } from 'react-dom/client'; import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'; import { AppShell } from '../shell/AppShell'; import { AppTextArea } from './AppTextArea'; import { AppTextBox } from './AppTextBox'
describe('text inputs', () => { let host: HTMLDivElement; let root: ReturnType<typeof createRoot>; beforeEach(() => { ;(globalThis as { IS_REACT_ACT_ENVIRONMENT?: boolean }).IS_REACT_ACT_ENVIRONMENT = true; host = document.createElement('div'); document.body.append(host); root = createRoot(host) }); afterEach(() => { act(() => root.unmount()); host.remove() })
  it('forwards refs, changes, clear actions, and localized labels', () => { const ref = createRef<HTMLInputElement>(); const onChange = vi.fn(); const onClear = vi.fn(); act(() => root.render(<AppShell locale="zh-CN"><AppTextBox clearable defaultValue="Ada" onChange={onChange} onClear={onClear} ref={ref} /><AppTextBox loading /></AppShell>)); expect(ref.current?.value).toBe('Ada'); expect(host.querySelector('button')?.getAttribute('aria-label')).toBe('清除输入'); expect(host.querySelector('[role=status]')?.getAttribute('aria-label')).toBe('正在加载'); act(() => host.querySelector('button')?.click()); expect(onClear).toHaveBeenCalledOnce(); expect(ref.current?.value).toBe('') })
  it('does not offer clear for passwords, disabled, or read-only values', () => { act(() => root.render(<><AppTextBox clearable defaultValue="secret" type="password" /><AppTextBox clearable defaultValue="x" disabled /><AppTextBox clearable defaultValue="x" readOnly /></>)); expect(host.querySelector('button')).toBeNull() })
  it('counts controlled and uncontrolled textarea content', () => { act(() => root.render(<><AppTextArea defaultValue="hello" maxLength={10} showCount /><AppTextArea showCount value="abc" readOnly /></>)); expect(host.textContent).toContain('5 / 10'); expect(host.textContent).toContain('3') })
  it('includes padding and borders in auto-resize row limits', () => { Object.defineProperty(HTMLTextAreaElement.prototype, 'scrollHeight', { configurable: true, value: 80 }); act(() => root.render(<AppTextArea autoResize maxRows={3} minRows={2} style={{ borderBottomWidth: 1, borderTopWidth: 1, boxSizing: 'border-box', lineHeight: '20px', paddingBottom: 6, paddingTop: 4 }} />)); expect(host.querySelector('textarea')?.style.height).toBe('72px') })
  it('normalizes maxRows below minRows and observes width changes', () => { const observe = vi.fn(); const disconnect = vi.fn(); vi.stubGlobal('ResizeObserver', class { observe = observe; disconnect = disconnect }); Object.defineProperty(HTMLTextAreaElement.prototype, 'scrollHeight', { configurable: true, value: 20 }); act(() => root.render(<AppTextArea autoResize maxRows={2} minRows={4} style={{ borderWidth: 0, boxSizing: 'border-box', lineHeight: '10px', padding: 0 }} />)); expect(host.querySelector('textarea')?.style.height).toBe('40px'); expect(observe).toHaveBeenCalledWith(host.querySelector('textarea')); act(() => root.unmount()); expect(disconnect).toHaveBeenCalledOnce(); root = createRoot(host); vi.unstubAllGlobals() })
})
