import { cloneElement, useEffect, useId, useRef, useState, type CSSProperties, type MouseEvent, type ReactElement, type Ref } from 'react'; import { createPortal } from 'react-dom'; import { useAppOverlayHost } from '../overlay/AppOverlayHostContext'; import { composeEventHandlers, getElementRef, useMergedRefs } from '../overlay/trigger'; import { useAnchoredOverlayPosition } from '../overlay/useAnchoredOverlayPosition'; import { useOverlayDismiss } from '../overlay/useOverlayDismiss'; import { OVERLAY_SURFACE_FALLBACK_STYLE } from '../overlay/surfaceFallback'; import type { AppPopoverProps } from './types'; import './AppPopover.css'
interface TriggerProps { onClick?: (event: MouseEvent<HTMLElement>) => void; 'aria-controls'?: string; 'aria-expanded'?: boolean; 'aria-haspopup'?: 'dialog'; ref?: Ref<HTMLElement> }
export function AppPopover({ ariaLabel = 'Popover', children, className, closeOnEscape = true, closeOnOutsideClick = true, defaultOpen = false, initialFocusRef, matchTriggerWidth = false, modal = false, offset = 6, onOpenChange, open, placement = 'bottom-start', style, trigger }: AppPopoverProps) {
  const controlled = open !== undefined; const [internal, setInternal] = useState(defaultOpen); const visible = controlled ? open : internal; const triggerRef = useRef<HTMLElement | null>(null); const overlayRef = useRef<HTMLDivElement | null>(null); const [triggerWidth, setTriggerWidth] = useState<number>(); const wasOpen = useRef(visible); const overlayHost = useAppOverlayHost(); const id = useId()
  const setVisible = (next: boolean) => { if (!controlled) setInternal(next); onOpenChange?.(next) }
  const position = useAnchoredOverlayPosition({ open: visible, triggerRef, overlayRef, preferredPlacement: placement, gap: Math.max(0, offset), viewportPadding: 10, dependencies: [matchTriggerWidth, typeof children === 'string' ? children : null] })
  useEffect(() => { if (visible && matchTriggerWidth) setTriggerWidth(triggerRef.current?.getBoundingClientRect().width); else if (!visible) setTriggerWidth(undefined) }, [matchTriggerWidth, visible])
  useEffect(() => { if (visible && initialFocusRef?.current) requestAnimationFrame(() => initialFocusRef.current?.focus({ preventScroll: true })); if (wasOpen.current && !visible) triggerRef.current?.focus({ preventScroll: true }); wasOpen.current = visible }, [initialFocusRef, visible])
  useOverlayDismiss({ open: visible, triggerRef, overlayRef, onDismiss: () => setVisible(false), closeOnEscape, closeOnOutsidePointerDown: closeOnOutsideClick, closeOnExternalScroll: false, closeOnResize: false, closeOnWindowBlur: false })
  const child = trigger as ReactElement<TriggerProps>; const mergedRef = useMergedRefs(getElementRef(child), triggerRef); const renderedTrigger = cloneElement(child, { 'aria-controls': visible ? id : undefined, 'aria-expanded': visible, 'aria-haspopup': 'dialog', onClick: composeEventHandlers(child.props.onClick, () => setVisible(!visible)), ref: mergedRef })
  if (!visible || typeof document === 'undefined') return renderedTrigger
  return <>{renderedTrigger}{createPortal(<div aria-label={ariaLabel} aria-modal={modal} className={['app-popover', className].filter(Boolean).join(' ')} data-placement={position.placement} id={id} ref={overlayRef} role="dialog" style={{ ...(overlayHost ? undefined : OVERLAY_SURFACE_FALLBACK_STYLE), ...style, left: position.x, maxHeight: position.measured ? position.maxHeight : undefined, maxWidth: position.measured ? position.maxWidth : undefined, minWidth: matchTriggerWidth ? triggerWidth : undefined, pointerEvents: position.measured ? undefined : 'none', top: position.y, visibility: position.measured ? 'visible' : 'hidden' } as CSSProperties}>{children}</div>, overlayHost ?? document.body)}</>
}
